### ISSUE TITLE
Building type not correctly processed in 0.6.8 version

### ISSUE THREAD

**Issue by gidema** [gidema/josm-ods-bag#12]
In the 0.6.8 version of the plug-in, all building get building=yes in stead of a proper type.

**Comment by gidema** [comment]
The problem doesn't seem to be consistent. At least in the development environment this issue didn't occur the last time I checked.

**Comment by Kars-de-Jong** [comment]
It seems to occur more often / always when you first download an area, then zoom out slightly and select 'Download' again from the ODS menu. Then, when using the ODS stylesheet, the buildings with issues show up in a purple-ish colour. For those buildings, only '|ODS=true' tag is present, no other ones (such as '|ODS:statusMatch').

**Comment by gidema** [comment]
The problem seems to be resolved. I can't reproduce it.
