### ISSUE TITLE
ODS-Plugin - RESET bevestigen

### ISSUE THREAD

**Issue by CJTmmr** [gidema/josm-ods-bag#15]
Goedemorgen,

Pas had ik een paar panden ge-updatet, maar nog niet ge-upload...
Bij de volgende panden om te updaten, drukte ik per ongeluk met de muis op RESET i.p.v. UPDATE:
​
![update reset](https://cloud.githubusercontent.com/assets/15076257/18706231/74437cfe-7ff1-11e6-857a-b175fc17bb48.jpg)
en je snapt het al - 5 minuten werk weg.
Kan de RESET om een bevestiging vragen?
En misschien een toepasselijk icoontje?

Bedankt,

Kees-Jan

**Comment by gidema** [comment]
(Suggesties voor) icoontjes zijn altijd welkom.

**Comment by gidema** [comment]
See josm-openservices issue 51.
