### ISSUE TITLE
Warnings Old style SideButton

### ISSUE THREAD

**Issue by SanderH** [gidema/josm-ods-bag#19]
Hier nog een paar warnings die ik langs zag komen bij het opstarten:

- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.ods.gui.AbstractDownloadDialog$DownloadAction@2f66db02
- W: Old style SideButton usage for action org.openstreetmap.josm.plugins.ods.gui.AbstractDownloadDialog$CancelAction@5250a199

In diverse JOSM plugins zijn de laatste maanden ook al diverse warnings opgelost: https://josm.openstreetmap.de/ticket/12994

**Comment by gidema** [comment]
Fixed in 0.6.10 for 0.6 branch.
Needs porting to 0.7 branch

**Comment by gidema** [comment]
Fixed in 0.7 branch
