### ISSUE TITLE
Tag "|ODS:nevenadres" verwijderen bij upload

### ISSUE THREAD

**Issue by SanderH** [gidema/josm-ods-bag#20]
Kan de plugin uitgebreid worden om de tag "|ODS:nevenadres" automatisch te verwijderen?
Zie ook https://forum.openstreetmap.org/viewtopic.php?pid=634457

**Comment by de-vries** [comment]
Misschien is het iets robuster om `|ODS:*` automatisch te verwijderen?

**Comment by gidema** [comment]
```|ODS:*``` Automatisch verwijderen is helaas geen optie zonder Josm te verbouwen. Anders had het er al lang ingezeten.
```|ODS:nevenadres``` automatisch verwijderen is wel mogelijk en ga ik meenemen in een volgende versie.
Heeft iemand nog een goede suggestie voor een engelse vertaling van 'nevenadres'?

**Comment by de-vries** [comment]
Als ik op internet rond zoek hoe andere baggebruikers dat doen kom ik de termen 'additonal address' en 'secondary address' tegen. mij lijkt 'secondary address' het meest beschrijvend.

**Comment by SanderH** [comment]
`secondary address` lijkt inderdaad het meest geschikt en had ik ook al zo op de legenda staan als engelse vertaling in de legenda.
Zal ik er dan |ODS:secondaryaddress van maken in de GeoJSON?

**Comment by gidema** [comment]
+1 Gertjan

**Comment by SanderH** [comment]
>> Zal ik er dan |ODS:secondaryaddress van maken in de GeoJSON?

>+1 Gertjan

Is aangepast.

**Comment by gidema** [comment]
Het is toch gelukt om alle |ODS tags te verwijderen bij uploads.

**Comment by gidema** [comment]
TODO Implement in 0.7 as well.
