### ISSUE TITLE
Onderscheid in status ingemeten of niet

### ISSUE THREAD

**Issue by SanderH** [gidema/josm-ods-bag#21]
Zou je onderscheid kunnen maken in status van inmeten zodat de mapcss dat onderscheid kan weergeven?
Bijvoorbeeld zoiets:
```
|ODS:status=in_use
|ODS:status=in_use not measured
```
Voor respectievelijk "Pand in gebruik" en "Pand in gebruik (niet ingemeten)"

**Comment by gidema** [comment]
Ga ik doen.

**Comment by gidema** [comment]
Fixed in 0.6 and 0.7 branch.
