### ISSUE TITLE
reset adviseert te resetten

### ISSUE THREAD

**Issue by de-vries** [gidema/josm-ods-bag#22]
> Ik krijg wel na ODS-Reset de melding ODS Layer removed. You removed one of the layers that belong to the BAG module...you have to reset the module"
> En dat deed ik juist!

bron: https://forum.openstreetmap.org/viewtopic.php?pid=637216#p637216

**Comment by gidema** [comment]
Dit is niet specifiek voor josm-ods-bag. Zie daarom https://github.com/gidema/josm-openservices/issues/63
