### ISSUE TITLE
BuildingType enum: OTHER kan maar een keer voorkomen

### ISSUE THREAD

**Issue by jdhoek** [gidema/josm-ods-bag#31]
In de enum `BuildingType` staat een `OTHER` waarde, met een static method waarmee je die kan instantiëren:

```java
    public static BuildingType OTHER(String subType) {
        BuildingType other = OTHER;
        other.subType = subType;
        return other;
    }
```

Dit, een variabele waarde in een enum, kan in talen zoals Rust, maar in Java is een enum heel strikt: elke enumwaarde kan runtime maar één keer voorkomen. Dat is ook de reden dat je enums met elkaar mag vergelijken met `=` in plaats van `equals()`.

In Java stop je ook wel waarden in een enum, maar dat zijn dan statische waarden. Deze `OTHER` werkt nu alleen zoals je dat verwacht wanneer de waarde die je er in zet altijd dezelfde is, of niet relevant is.

In een unittest kun je dit gedrag goed zien:

```java
    @Test
    public void test() {
        BuildingType otherA = BuildingType.OTHER("A");
        BuildingType otherB = BuildingType.OTHER("B");

        // Faalt:
        assertThat(otherA, is(not(otherB)));
        
        // Faalt:
        assertThat(otherA.getSubType(), is("A"));
        
        // Werkt:
        assertThat(otherA, is(otherB));
        assertThat(otherA.getSubType(), is("B"));
        assertThat(otherB.getSubType(), is("B"));
    }
```

Ik kan zo niet zien of dit nu problemen oplevert in de code, maar ik zou de `subType` uit de enum halen.

**Comment by gidema** [comment]
Goed punt. Other was bedoeld om bijzondere OSM gebouwtypes als building=roof vast te leggen. Dit stamt nog uit de tijd dat er geen onderscheid was tussen OdBuilding en OsmBuilding. De methode  getSubType() werd 1 keer aangeroepen:
`        case OTHER:
            type = building.getBuildingType().getSubType();
`
Daar is building een OdBuilding, dus zal buildingType nooit OTHER zijn.
subType kan dus veilig verwijderd worden.
